title: Kenneth Foo - Portfolio
email: kfoofw@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
permalink: ':title/'
# baseurl: "" # For testing of jekyll serve. run command "bundle exec jekyll serve"
baseurl:  "https://kfoofw.github.io" # the subpath of your site, e.g. /blog
url:  # the base hostname & protocol for your site, e.g. http://example.com

# Author settings
author: Kenneth Foo Fangwei
author-pic: kfoo.jpg
about-author: "Hi there! My name is Kenneth Foo and I'm originally from Singapore. I’m graduated with a Master of Data Science degree from the University of British Columbia, and I'm currently working as a Senior Quantitative Engineer in OPALai (https://www.opalai.com/). With a passion for product data science and personalisation using machine learning, my key interests lies in topics such as bandit algorithms, online learning, Bayesian statistics,
time series prediction, and causality frameworks."

# Contact links
email: kfoofw@gmail.com # Add your Email address
phone: +1-236-986-3645 # Add your Phone number
website: kfoofw.github.io # Add your website, do not add http://
linkedin: kfoofw # Add your Linkedin handle
github: kfoofw # Add your Github handle
# twitter:  # Add your Twitter handle
# facebook: # Add your Facebook handle
# instagram: # Add your Instagram handle
# pinterest: # Add your Pinterest handle

# Newsletter
# mailchimp: # Add your MailChimp form identifier.

# Disqus
# discus_identifier: # Add your discus identifier

# Tracker
# analytics: # Google Analytics

# Paginate
paginate: 8
paginate_path: /page:num/

# Build settings
markdown: kramdown

plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap

include: [_pages]
exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock", "package-lock.json", "assets/css/sass/"]
